name: safepull
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  audioplayers: ^6.4.0
  http: ^1.4.0
  intl: ^0.19.0
  provider: ^6.1.1
  crypto: ^3.0.3
  shared_preferences: ^2.2.2

  # âœ… Firebase dependencies
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_analytics: ^11.4.6
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  syncfusion_flutter_charts: ^29.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
